[project]
name = "trafikinfo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.8.10"
dependencies = [
    "flask>=3.0.3",
    "python-dotenv>=1.0.1",
    "requests>=2.32.4",
]
